logging:
  level:
    root: INFO

server:
  port: 8080

redis:
  server:
    urls: >
      http://redis-cluster-0001-001.7uhivk.0001.use1.cache.amazonaws.com:6379,
      http://redis-cluster-0001-002.7uhivk.0001.use1.cache.amazonaws.com:6379,
      http://redis-cluster-0002-001.7uhivk.0001.use1.cache.amazonaws.com:6379,
      http://redis-cluster-0002-002.7uhivk.0001.use1.cache.amazonaws.com:6379,
      http://redis-cluster-0003-001.7uhivk.0001.use1.cache.amazonaws.com:6379,
      http://redis-cluster-0003-002.7uhivk.0001.use1.cache.amazonaws.com:6379