apiVersion: v1
kind: Service
metadata:
  name: redisson-sample-svc
  labels:
    app: redisson-sample
    component: redisson-sample-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    component: redisson-sample-deploy
